server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.17.0.2:8761/eureka
  instance:
    hostname: 43.200.189.164
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            maxAge: 3600

      routes:
        - id: novels-service
          uri: lb://NOVELS-SERVICE
          predicates:
            - Path=/novels-service/**
          filters:
            - StripPrefix=1
        - id: sections-service
          uri: lb://SECTIONS-SERVICE
          predicates:
            - Path=/sections-service/**
          filters:
            - StripPrefix=1
        - id: payments-service
          uri: lb://PAYMENTS-SERVICE
          predicates:
            - Path=/payments-service/**
          filters:
            - StripPrefix=1
        - id: config-server
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config-server/**
          filters:
            - StripPrefix=1
        - id: users-service
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users-service/**
          filters:
            - StripPrefix=1
        - id: utils-service
          uri: lb://UTILS-SERVICE
          predicates:
            - Path=/utils-service/**
          filters:
            - StripPrefix=1